export enum IPermissions {
  USER_MANAGEMENT = 'USER_MANAGEMENT',
  CREATE_POST = 'CREATE_POST',
  PUBLISH_OWN_POST = 'PUBLISH_OWN_POST',
  PUBLISH_ANY_POST = 'PUBLISH_ANY_POST',
  EDIT_ANY_POST = 'EDIT_ANY_POST',
  DELETE_OWN_POST = 'DELETE_OWN_POST',
  DELETE_ANY_POST = 'DELETE_ANY_POST',
  CREATE_PAGES = 'CREATE_PAGES',
  EDIT_PAGES = 'EDIT_PAGES',
  DELETE_PAGES = 'DELETE_PAGES',
}
